FROM golang:1.7.3 as build
WORKDIR /go/src/webserver
RUN go get -d -v golang.org/x/net/html  
COPY webserver.go .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .
FROM scratch  
WORKDIR /
COPY --from=build /go/src/webserver/app .
CMD ["./app"]  